####################
# GROUND REMOVAL
####################

# SMOOTH WINDOW
smooth_window_size_front: 11
smooth_window_size_left: 11
smooth_window_size_right: 11

# GROUND REMOVAL THRESHOLD
ground_remove_angle_front: 18
ground_remove_angle_left: 18
ground_remove_angle_right: 18

# TOPIC PREFIX
topic_prefix: "11_18"





