####################
# GROUND REMOVAL
####################

# SMOOTH WINDOW
smooth_window_size_front: 5
smooth_window_size_left: 5
smooth_window_size_right: 5

# GROUND REMOVAL THRESHOLD
ground_remove_angle_front: 27
ground_remove_angle_left: 27
ground_remove_angle_right: 27

# TOPIC PREFIX
topic_prefix: "5_27"





