####################
# GROUND REMOVAL
####################

# SMOOTH WINDOW
smooth_window_size_front: 9
smooth_window_size_left: 9
smooth_window_size_right: 9

# GROUND REMOVAL THRESHOLD
ground_remove_angle_front: 27
ground_remove_angle_left: 27
ground_remove_angle_right: 27

# TOPIC PREFIX
topic_prefix: "9_27"





